### ISSUE TITLE
BF: New wrapper for bf.systems.System

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro-Int-Gymnasium#7]
**Description/Motivation**
This new wrapper class shall enable Gymnasium environments as pure state-based systems to be controlled with a classic controller (e.g., PID controller). The reward functionality is ignored on this level since the classic controller has a 'hard-wired' strategy within.

**Hint**
Probably the existing functionality of the current wrapper can be transferred and reused by inheritance...

**Task list**
- [ ] 1. Introduction of sub-packages wrappers.bf and wrappers.rl
- [ ] 2. Implementation
    - [ ] 2.1 New class bf.WrSysGYM2MLPro
    - [ ] 2.2 New class bf.WrSysMLPro2GYM
    - [ ] 2.3 New class rl.WrEnvGYM2MLPro (inherits from bf.WrSysGYM2MLPro)
    - [ ] 2.4 New class rl.WrEnvMLPro2GYM (inherits from bf.WrSysMLPro2GYM) 
- [ ] 3. Backward compatibility
    - [ ] Add suitable entries to wrappers.__init__.py
- [ ] 4. Suitable howtos
- [ ] 5. RTD documentation

**Comment by detlefarend** [comment]
Discarded because class rl.Environment inherits from bf.systems.System and should therefore be backwards compatible.
